name: course_tdd
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:  
  intl: ^0.16.1
  carousel_slider: ^2.3.1
  localstorage: ^3.0.3+6
  flutter_secure_storage: ^3.3.5
  get: ^3.22.2
  equatable: ^1.2.5
  provider: ^4.3.2+2
  http: ^0.12.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.5
  mockito: ^3.0.0
  faker: ^1.2.1
  flutter_launcher_icons: ^0.8.1
  image_test_utils: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png
